server:
  port: 8095
  servlet:
    context-path: /

application:
  jwt:
    secretKey:  MySecretKeyThatShouldBeVeryLongMySecretKeyThatShouldBeVeryLongMySecretKeyThatShouldBeVeryLong
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 4
spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.26.196.7:1521/prodbs.emdad.com
    username: opr
    password: ops139810
#  hikari:
#    minimumIdle: 5
#    maximumPoolSize: 25
#    idleTimeout: 30000
#    maxLifetime: 2000000
#    connectionTimeout: 30000
#    poolName: HikariPoolOPR
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
